# Project Setup - Library Load

library(xml2)
library(readxl)
library(readr)
library(tidyr)
library(dplyr)
library(purrr)
library(ggplot2)
library(lubridate)
library(directlabels)
library(lubridate)
library(broom)
library(scales)
library(ggmap)
library(maps)
library(mapdata)
library(WVPlots)
library(rgdal)
library(rgeos)
library(ggforce)
library(maptools)
library(stringr)
library(ranger)
library(vtreat)
library(xgboost)

# Set options to limit sci notation and decimal places
options(scipen = 999, digits = 3)