---
title: "Springboard Capstone – Initial Project Ideas"
author: "Jim Scotland"
date: "February 21, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
  
  

###Diabetes Insulin & Glucose Management
__PROBLEM__: Diabetics need to maintain blood glucose levels (BGL) within a designated range. Excessive high levels lead to long-term organ damage. Excessive lows run the more immediate risks of coma or death.

__GOAL__: Analyze timestamped BGL and insulin data from a variety of patients to determine if there is a best approach to maintain healthy BGL levels and if patterns of risk emerge.

__DATA__: The Diabetes dataset AIM-94 comes from the AI in Medicine symposium. The data includes BGL log data from 70 patients over varying periods of time. The data was assembled in 1994 and includes four variables: date, time, BGL/Insulin readings and a descriptive code. It is contained in 70 separate data files. Two additional text files outline data coding methodology and describe diabetes management issues generally.

__DATA SOURCE__:  
<https://archive.ics.uci.edu/ml/datasets/diabetes>  


###Murder-Suicide Predictors & Prevention
__PROBLEM__: Many homicides are committed by individuals who then commit suicide. The problem is most notable in mass shooting incidents. A more common aspect, however, involves family members who shoot their spouses and/or children prior to taking their own lives.

__GOAL__: Analyze Murder-Suicide incidents to determine if factors like gun ownership levels, gun law restrictions, geography, poverty, education or others might impact the prevalence of these incidents. Identify specific strategies to reduce the frequency of murder-suicide episodes.

__DATA__: The Gun Violence Archive collects data on reported gun violence situations going back to 2014. The Centers for Disease Control also tracks firearm related mortality data but does not report on specific incidents of murder-suicide. The Giffords Law Center and the Boston University School of Public Health provide data on state level gun laws. Additional demographic data is available from the US Census website.

__DATA SOURCES__:  
<http://www.gunviolencearchive.org>  
<https://wonder.cdc.gov>  
<https://factfinder.census.gov>  
<https://www.statefirearmlaws.org>  
<http://lawcenter.giffords.org>  


###College Towns and Home Value Growth
__PROBLEM__: Does the presence of higher education institutions drive above-average home value growth? Does the rank of the institution influence this effect if it exists?

__GOAL__: Analyze home value growth rates in college towns compared to non-college towns and determine the effective geographic range of the above-average growth effect if it exists.

__DATA__: Zillow Home Value Data, US News & World Report

__DATA SOURCES__:  
<https://www.zillow.com/research/data>  
<https://www.usnews.com/best-colleges>  

